Throw error when git log not found by writer.py
pyvideo/pyvideo pull request #134
Opened 2017-12-23 22:10 UTC by SarahPythonista

If git log timestamp is not found, raise RuntimeError with a descriptive message.
for issue #133

2017-12-28 22:29 UTC, SarahPythonista commented
Originally closed PR due to Travis-CI test failure. Re-opening in light of #117 and pyvideo/data issue [431](https://github.com/pyvideo/data/issues/431).

2019-10-26 00:26 UTC, logston requested changes

2019-10-26 00:26 UTC, logston commented on plugins/writer.py
> +                if not output:
This is going to throw a name error. We would need it after the following line.

2019-12-08 17:44 UTC, cyrus303 approved these changes

2020-11-28 18:56 UTC, closed without merging