Support PeerTube video
pyvideo/pyvideo pull request #269
Opened 2020-04-01 20:21 UTC by pilou-

Support PeerTube video.

Screenshot with the added PeerTube tab added:
![Screenshot_2020-04-01_22-17-43](https://user-images.githubusercontent.com/1356830/78182658-2b425b80-7456-11ea-8c46-d9e21911d02e.png)

2020-08-20 07:34 UTC, logston requested changes

2020-08-20 07:34 UTC, logston commented on plugins/json_reader.py
> +    embed_url = [x for x in url_parsed]
```suggestion
    embed_url = list(url_parsed)
```

2020-08-20 07:35 UTC, logston commented
Thanks for the unittests!

2020-08-26 00:05 UTC, pilou- commented on plugins/json_reader.py
> +    embed_url = [x for x in url_parsed]
Updated

2020-08-26 04:25 UTC, logston approved these changes

2020-08-26 04:26 UTC, merged