Fix wrong youtube.com URL for youtu.be domain
pyvideo/pyvideo pull request #287
Opened 2021-08-29 12:18 UTC by finn0

For videos, whose URL contains "youtu.be" domain, we're getting an extra
"/" between "www.youtube.com" and "video id" in actual video URL.

Resolves: #286

2021-08-29 20:56 UTC, logston commented
Thanks @finn0! Can we update this to use `urllib.parse.urlparse` and `.path`? That way we have a more semantic solution?

2021-08-30 12:01 UTC, finn0 commented
On 8/29/21 8:56 PM, Paul Logston wrote:
> Thanks @finn0! Can we update this to use `urllib.parse.urlparse` and `.path`? That way we have a more semantic solution?
> 

Sorry, I didn't get your question properly. Aren't we already using
`urllib.parse`? I've only done a minor change by adding "[1:]" at end 
".path". If you're asking for something else to be changed, that should 
be an another merge request.

2021-09-18 22:04 UTC, logston requested changes

2021-09-18 22:04 UTC, logston commented on plugins/json_reader.py
> +        video_id = url_parsed.path[1:]
```suggestion
        video_id = url_parsed.path.lstrip("/")
```

2021-09-18 22:04 UTC, logston commented
Pardon, I wasn't clear. I'm concerned about stripping a first character without knowing what that char is. Can we switch this to `.lstrip("/")`?

2021-09-19 11:42 UTC, finn0 commented on plugins/json_reader.py
> +        video_id = url_parsed.path[1:]
Sure, just pushed suggested change.

2021-09-19 12:09 UTC, finn0 commented
>  I'm concerned about stripping a first character without knowing what that char is.

I was removing first character in `elif 'youtu.be/' in url:` because we're always going to get an extra `/` at beginning of id, but it's a good idea to check it first, then remove it.

I've few questions:
- After force pushing my changes, there is a conflict in the branch. Should I resolve it, also?
- Also, `_get_youtube_url()` function doesn't handle the case when URL format is `https://www.youtube.com/embed/` (https://www.youtube.com/embed/hZ7hgYKKnF0) or `https://www.youtube-nocookie/embed/` (https://www.youtube-nocookie/embed/hZ7hgYKKnF0). I can think of two reasons to not handle this case, either we're expecting contributor to not use `https://www.youtube.com/embed/`format for URLs in data files or we're handling this case somewhere else in the code base.

2021-09-19 16:54 UTC, logston commented
Hi @finn0, thanks for the update! Yes a simple rebase should resolve the issue re: merge conflict. 

As for our `_get_youtube_url`, correct, we don't allow URLs of the forms you described at this time. Our tooling is built to pull out other forms of youtube URLs.

2021-09-20 03:08 UTC, finn0 commented
@logston, did you intend to do a [force push](https://github.com/pyvideo/pyvideo/pull/287#event-5323860395) on `master` branch? Usually, people recommend to not do any force push on main development branch (for example: `master`/`main`), we might lose some commits and make things harder for people whose work based on commits before the force push.

In our case, we've lost these [4 commit](https://github.com/pyvideo/pyvideo/pull/287#commits-pushed-db9b958). If this is intended, I can still fix merge conflict. I asking this question just for clarity.

2021-09-20 17:46 UTC, logston commented
My apologies @finn0. I'll protect the branch so that does not happen again. Your `data` dir changes should still be present in that repo. Once rebased, I can merge this PR in.

2021-09-21 12:49 UTC, finn0 commented
Hi! @logston, I've rebased the branch. Can you review it once again?

2021-09-22 20:11 UTC, merged

2021-09-22 20:11 UTC, logston commented
Thanks!